config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  devise_for :users
  resources :users
  resources :illusts

  resources :users do
    member do
        get :following, :followers
    end
  end
  resources :followfollowers, only: [:create, :destroy]
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/followfollower.rb
class Followfollower < ApplicationRecord
      #自分をフォローしているユーザー
      belongs_to :follower, class_name: "User"
      #自分がフォローしているユーザー
      belongs_to :following, class_name: "User"
      #バリデーション
      validates :follower_id, presence: true
      validates :following_id, presence: true
end

app/models/illust.rb
class Illust < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  mount_uploader :avatar, AvatarUploader
 
 
  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :illust
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  mount_uploader :avatar, AvatarUploader
  mount_uploader :image, ImageUploader
  has_many :illusts, dependent: :destroy
  
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Followfollower", dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Followfollower", dependent: :destroy
  has_many :followers, through: :follower_relationships

 #フォローしているかを確認するメソッド
 def following?(user)
   following_relationships.find_by(following_id: user.id)
 end

 #フォローするときのメソッド
 def follow(user)
   following_relationships.create!(following_id: user.id)
 end

 #フォローを外すときのメソッド
 def unfollow(user)
   following_relationships.find_by(following_id: user.id).destroy
 end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    new_user_session_path # ログアウト後に遷移するpathを設定
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/followfollowers_controller.rb
class FollowfollowersController < ApplicationController
  before_action :authenticate_user!

  def create
    @User = User.find(params[:following_id])
    current_user.follow(@User)
  end

  def destroy
    @User = User.find(params[:id])
    current_user.unfollow(@User)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @users = User.all
    @user = User.new
    @newillusts = Illust.order(created_at: :desc).limit(21)
  end
end

app/controllers/illusts_controller.rb
class IllustsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @illusts = Illust.order(created_at: :desc).limit(21)
  end

  def show
    # @User = User.find(params[:id])
    @illust = Illust.find(params[:id])
    @user = User.find_by(id: @illust.user_id)
    @illusts = @user.illusts.page(params[:page]).per(6).order('created_at DESC')
  end

  def new
    @illust = Illust.new
  end

  def create
    @illust = current_user.illusts.build(illust_params)
    if @illust.save
      redirect_to illust_path(@illust), notice: "作品を投稿しました。"
    else
      render :new
    end
  end

  def edit
    @illust = Illust.find(params[:id])
    if @illust.user != current_user
        redirect_to illustes_path, alert: "不正なアクセスです。"
    end
  end

  def update
    @illust = Illust.find(params[:id])
    if @illust.update(illust_params)
      redirect_to illust_path(@illust), notice: "作品情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    illust = Illust.find(params[:id])
    illust.destroy
    redirect_to user_path(illust.user), notice: "作品を削除しました。"
  end


  private
  def illust_params
    params.require(:illust).permit(:title, :body, :image, :avatar)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @User = User.find(params[:following_id])
    current_user.follow(@User)
  end

  def destroy
    @User = User.find(params[:id])
    current_user.unfollow(@User)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
    @User = User.find(params[:id])
  end

  def create
    @user = current_user.build(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :show
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def following
    #@userがフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    #@userをフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :avatar, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/illusts_helper.rb
module IllustsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followfollowers/create.js.erb
$("#follow_form").html('<%= j(render("users/unfollow")) %>');

<!-- フォロー数のカウント -->
$(".follow").html('<%= link_to following_user_path(@User) do %><h6 id="follow" style="color: #dbdbdb;">フォロー<%= @User.following.count %>人</h6><% end %>');

<!-- フォロワー数のカウント -->
$(".follower").html('<%= link_to followers_user_path(@User) do %><h6 id="follower" style="color: #dbdbdb;">フォロワー<%= @User.followers.count %>人</h6><% end %>');

app/views/followfollowers/destroy.js.erb
$("#follow_form").html('<%= j(render("users/follow")) %>');

<!-- フォロー数のカウント -->
$(".follow").html('<%= link_to following_user_path(@User) do %><h6 id="follow" style="color: #dbdbdb;">フォロー<%= @User.following.count %>人</h6><% end %>');

<!-- フォロワー数のカウント -->
$(".follower").html('<%= link_to followers_user_path(@User) do %><h6 id="follower" style="color: #dbdbdb;">フォロワー<%= @User.followers.count %>人</h6><% end %>');

app/views/homes/top.html.erb
<% if user_signed_in? %>

<div class="div_wrapper">
      <div style="color: white; font-size: 30px;">最新</div>
      <ul class="ul_Wrap">
        <% @newillusts.each do |illust| %>
          <li class="li_ImageW">
            <div class="ImageUser">
              <%= link_to illust_path(illust), data: {"turbolinks" => false} do %>
                <% if illust.image? %>  <!-- アップロード画像がある場合に実行する -->
                  <%= image_tag illust.image.url, class: "IMGIllust", width: "160", height: "160" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
                <% end %>
              <% end %>
            </div>

            <div class="Illust_index">
              <%= link_to illust_path(illust), style: "color: white;", data: {"turbolinks" => false} do %>
                <%= illust.title %>
              <% end %>
            </div>
 
          </li>
        <% end %>
      </ul>
</div>



<% else %>

<div id="wrapper">
  <%= form_for(@user) do |f| %>
  
    <h2>新規登録</h2>
    <div class="box-name">
      <%= f.label :username %><br />
      <%= f.text_field :username, autofocus: true, autocomplete: "username" %>
    </div>

    <div class="box-email">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="box-password">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="box-password">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="box-login">
      <%= f.submit "新規登録する" %>
    </div>
  <% end %>

      <div class="box-newusr">
        <p><span>------------</span> 既に登録されていますか？ <span>------------</span></p>
        <%= link_to "ログイン", new_user_session_path %>
      </div>
</div>

<% end %>

app/views/illusts/edit.html.erb
<div>
  <div style="margin-top: 30px;">
    <h2 style="text-align:center">作品編集</h2>
  </div>

  <%= form_for @illust do |f| %>
    <div class="Illust_New_wrapper">

          <div class="field">
            <div><%= f.label :image, "作品", class: "label" %></div>
            <div><%= f.file_field :image, class: "input" %></div>
          </div>

          <div class="field">
            <div><%= f.label :title, "タイトル", class: "label" %></div>
            <div><%= f.text_field :title, class: "input" %></div>
          </div>

          <div class="field">
            <div><%= f.label :body, "キャプション", class: "label" %></div>
            <div><%= f.text_area :body, class: "textarea" %></div>
          </div>

          <%= f.submit '編集を完了', class: "button is-success" %>
    </div>
  <% end %>
</div>

app/views/illusts/index.html.erb
<div  class="div_wrapper">
  <% @illusts.each do |illusts| %>

        <div class="ImageUser">
          <%= link_to illust_path(illusts) do %>
            <% if illusts.image? %>  <!-- アップロード画像がある場合に実行する -->
              <%= image_tag illusts.image.url, class: "IMGIllust", width: "160", height: "160" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
            <% end %>
          <% end %>
        </div>

        <div class="illust_title">
          <%= illusts.title %>
        </div>

  <% end %>
</div>

app/views/illusts/new.html.erb
<div>
  <div style="margin-top: 30px;">
    <h2 style="text-align:center">作品投稿</h2>
  </div>

   <div class="Illust_New_wrapper">
    <%= form_for @illust do |f| %>
          <div class="field">
            <div><%= f.label :image, "作品", class: "label" %></div>
            <div><%= f.file_field :image, class: 'input' %></div>
 
          </div>

          <div class="field">
            <div><%= f.label :title, "タイトル", class: "label" %></div>
            <div><%= f.text_field :title, class: "input" %></div>
          </div>

          <div class="field">
            <div><%= f.label :body, "キャプション", class: "label" %></div>
            <div><%= f.text_area :body, class: "textarea" %></div>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
   
    <% end %>
  </div>
</div>

app/views/illusts/show.html.erb
<div class="div_wrapper">
  <div class="div_flex">
    <main class="main_wrapper">
      <% if @illust.image? %>  <!-- アップロード画像がある場合に実行する -->
        <%= image_tag @illust.image.url, class: "img_illust" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
      <% end %>

      <div class="aside_wrap_main">
        <div class="current_user">
            <%= link_to user_path(@user), class: "AVATARUSERC", data: {"turbolinks" => false} do %>
              <% if @user.avatar? %>  <!-- アップロード画像がある場合に実行する -->
                <%= image_tag @user.avatar.url, style: "object-fit:cover;", width: "70", height: "70", class: "rounded-circle" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
              <% end %>
                
                  <%= @user.username %>
               
            <% end %>
            <%= link_to "プロフィールを編集", edit_user_path(@user), style: "margin-left: 20px;", class: "Edit_profile", data: {"turbolinks" => false} %>
              
        </div>

        <div class="illust_index">
          <%= @illust.title %>
          <%= simple_format @illust.body %>
        </div>
        
        <div class="edit-delete_wrapper">
          <% if @illust.user.id === current_user.id %>
            <%= link_to edit_illust_path(@illust), class: "btn btn-primary", data: {"turbolinks" => false} do %>
               この作品を編集する
            <% end %>
            <%= link_to illust_path(@illust), method: :delete, class: "btn btn-danger", data: {"turbolinks" => false}, data: {confirm: "削除しますか？"} do %>
              この作品を削除する
            <% end %>
          <% end %>
        </div>
      
        <ul class="ul_Wrap">
          <% @illusts.each do |illust| %>
            <li class="li_ImageW">
              <div class="ImageUser">
                <%= link_to illust_path(illust), data: {"turbolinks" => false} do %>
                  <% if illust.image? %>  <!-- アップロード画像がある場合に実行する -->
                    <%= image_tag illust.image.url, class: "IMGIllust", width: "160", height: "160" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
                  <% end %>
                <% end %>
             </div>

             <div class="Illust_index">
               <%= illust.title %>
             </div>
            </li>
          <% end %>
        </ul>
      </div>

    </main>

    <aside> 

      <%= link_to user_path(@user), class: "AVATARUSERCUr", data: {"turbolinks" => false} do %>
        <% if @user.avatar? %>  <!-- アップロード画像がある場合に実行する -->
          <%= image_tag @user.avatar.url, style: "object-fit:cover;", width: "70", height: "70", class: "rounded-circle" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
        <% end %>
        <%= @user.username %>
      <% end %>
      <% if @user.id == current_user.id %>
        <%= link_to "プロフィールを編集", edit_user_path(@user), class: "Edit_profile", data: {"turbolinks" => false} %>
      <% else %>

  

      <% end %>

      <div class="illust_index">
        <%= @illust.title %>
        <%= simple_format @illust.body %>
      </div>

    <%#ここからいいね機能%>

    <%#ここまでいいね機能%>
    <div class="edit-delete_wrapper">
      <% if @illust.user.id === current_user.id %>
        <%= link_to edit_illust_path(@illust), class: "btn btn-primary", data: {"turbolinks" => false} do %>
          この作品を編集する
        <% end %>
        <%= button_to illust_path(@illust), id: "delete_illust", method: :delete, class: "btn btn-danger", data: {confirm: "削除しますか？"} do %>
          この作品を削除する
        <% end %>
      <% end %>
    </div>

      

      <ul class="ul_Wrap">
        <% @illusts.each do |illust| %>
          <li class="li_ImageW">
            <div class="ImageUser">
              <%= link_to illust_path(illust), data: {"turbolinks" => false} do %>
                <% if illust.image? %>  <!-- アップロード画像がある場合に実行する -->
                  <%= image_tag illust.image.url, class: "IMGIllust", width: "160", height: "160" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
                <% end %>
              <% end %>
            </div>

            <div class="Illust_index">
              <%= illust.title %>
            </div>
 
          </li>
        <% end %>
      </ul>

    </aside>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IllustCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'app' %>

  </head>

  <body>

  <nav class="heaDer_wrap">
    <%= link_to root_path, data: {"turbolinks" => false}, id: "APPname" do %>
      <h1 class="APPNAME">IllustCollection</h1>
    <% end %>
    <ul class="index_wrapper">
      <% if user_signed_in? %>
        <li class="index Appname">
          <h2><%= link_to "IllustCollection", root_path, class: "AppName", data: {"turbolinks" => false} %></h2>
        </li>
        <li class="index">
          <%= link_to "ユーザー一覧", users_path, id: "Index", data: {"turbolinks" => false} %>
        </li>
        <li class="index">
          <%= link_to "作品投稿", new_illust_path,class: "New_Post", id: "Index", data: {"turbolinks" => false} %>
        </li>
        <li class="index">
          <%= link_to "プロフィール", user_path(current_user), id: "Index", data: {"turbolinks" => false} %>
        </li>
        <li class="index">
          <%= button_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトします。よろしいですか？"}, id: "log_out" %>
        </li>
      <% else %>
        <li class="index Appname">
          <h2><%= link_to "IllustCollection", root_path, class: "AppName", data: {"turbolinks" => false} %></h2>
        </li>
        <li class="index">
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light", id: "Index", data: {"turbolinks" => false} %>
        </li>
        <li class="index">
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light", id: "Index", data: {"turbolinks" => false} %>
        </li>
      <% end %>
    </ul>
  </nav>


<!--768px以下で表示-->
  <div class="menu-btn">
    <span></span>
    <span></span>
    <span></span>
  </div>

  <nav class="gnavi__sp-style">
    <ul>
      <% if user_signed_in? %>
        <li class="index">
          <%= link_to "ホームへ", root_path, data: {"turbolinks" => false} %>
        </li>
        <li>
          <%= link_to "ユーザー一覧", users_path %>
        </li>
        <li class="index">
          <%= link_to "作品投稿", new_illust_path, data: {"turbolinks" => false} %>
        </li>
        <li class="index">
          <%= link_to "プロフィール", user_path(current_user), data: {"turbolinks" => false} %>
        </li>
        <li class="index">
          <%= button_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトします。よろしいですか？"}, id: "log_out" %>
        </li>
      <% else %>
        <li class="index">
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light", data: {"turbolinks" => false} %>
        </li>
        <li class="index">
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light", data: {"turbolinks" => false} %>
        </li>
      <% end %>
    </ul>
  </nav>
<!--/768px以下で表示-->




    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
 
  </body>
</html>

app/views/likes/_like.html.erb
<div class="like-link" id="like-link-<%= illust.id %>">
  <% if current_user.likes.find_by(illust_id: illust.id) %>
    <%= link_to unlike_path(illust.id), method: :delete, remote: true do %>
        <div class = "iine__button">❤️<%= illust.likes.count %></div>
    <% end %>
  <% else %>
    <%= link_to like_path(illust.id), method: :post, remote: true do %>
        <div class = "iine__button">♡️<%= illust.likes.count %></div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", illust: @illust  )) %>');

app/views/likes/unlike.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", illust: @illust  )) %>');

app/views/users/_follow.html.erb
<!-- フォローボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: followfollowers_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @User.id %>
  <%= f.submit "フォローする", style: "border-radius:30px;", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- フォローボタン(MYPAGEのユーザーがcurrent_userでなければ表示------------------------------------------------------>
<% if user_signed_in? && @User != current_user %>
  <div id="follow_form">
    <% if current_user.following?(@User) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<!-- フォロー解除ボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: followfollower_path(@User), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", style: "border-radius:30px;", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<div>
  <div style="margin-top: 30px;">
    <h2 style="text-align:center">ユーザー情報編集</h2>
  </div>

  <%= form_for @user do |f| %>
    <div class="Illust_New_wrapper">

          <div class="field">
            <div><%= f.label :avatar, class: "label" %></div>
            <div><%= f.file_field :avatar, class: "input" %></div>
          </div>
 
          <div class="field">
            <div><%= f.label :username, "ユーザー名", class: "label" %></div>
            <div><%= f.text_field :username, class: "input" %></div>
          </div>

          <div class="field">
            <div><%= f.label :profile, "プロフィール", class: "label" %></div>
            <div><%= f.text_area :profile, class: "textarea" %></div>
          </div>

          <div class="field">
            <%= f.submit '編集を完了', class: 'btn btn-primary' %>
          </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div  class="div_wrapper">
    <div id="CARD" class="card">
      <div style="font-size: 25px;" class="card-header">
        ユーザー一覧
      </div>
      <ul class="list-group list-group-flush">
        <div class="users">
          <% @users.each do |user| %>
            <li id="liGroup" class="list-group-item">
              <div class="current_user">
                <%= link_to user_path(user), class: "AVATARUSERCUR", data: {"turbolinks" => false} do %>
                  <% if user.avatar? %>  <!-- アップロード画像がある場合に実行する -->
                    <%= image_tag user.avatar.url,id: "IMAGEAVTS", class: "rounded-circle" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
                  <% end %>
                  <%= user.username %>
                <% end %>
              </div>
            </li>
          <% end %>
        </div>
      </ul>
    </div>
</div>

app/views/users/show.html.erb
<div class="div_wrapper">

  <div class="UserPwrap">
    <div class="Usrwrp">
      <div class="USERWRAPPER">
        <div class="avatarUser">
          <% if @User.avatar? %>  <!-- アップロード画像がある場合に実行する -->
            <%= image_tag @User.avatar.url, class: "rounded-circle", id: "useravatar" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
          <% end %>
        </div>
        
        <div class="userNaFW">
          <div class="FlexUserNaFW">
            <div class="username">
              <%= @User.username %>
            </div>
              <div class="FolWrap">
                <div class="follow">
                  <%= link_to following_user_path(@User.id), data: {"turbolinks" => false} do %>
                    <h6 style="color: #dbdbdb;">フォロー<%= @User.following.count %>人</h6>
                  <% end %>
                </div>
                <div class="follower">
                  <%= link_to followers_user_path(@User.id), data: {"turbolinks" => false} do %>
                    <h6  style="color: #dbdbdb;">フォロワー<%= @User.followers.count %>人</h6>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
          <div class="follow_form">
              <%= render "follow_form" %>
          </div>
          <% if @User.id == current_user.id %>
            <%= link_to edit_user_path(@User),style: "margin: auto 10px;", data: {"turbolinks" => false} do %>
              <div class="Edit_profile">
                <div class="EditProfile">
                  プロフィールを編集
                </div>
              </div>
            <% end %>
          <% end %>
       
      </div>
    </div>
  </div>





    <div style="color: white;">作品数：<%= @User.illusts.count %></div>
    <!--タブ-->
    <ul class="tab-group">
      <li class="tab is-active">プロフィール</li>
      <li class="tab">イラスト</li>
    </ul>

    <!--タブを切り替えて表示するコンテンツ-->
    <div class="panel-group">
      <%#A%>
      <div class="panel is-show">
        <div class="UserProfile">
          <%= @User.profile %>
        </div>
      </div>

      <%#B%>
      <div class="panel">
        <ul class="ul_Wrap">
          <% @User.illusts.each do |i| %>
            <li class="li_ImageW">
              <div class="ImageUser">
                <%= link_to illust_path(i), data: {"turbolinks" => false} do %>
                  <% if i.image? %>  <!-- アップロード画像がある場合に実行する -->
                    <%= image_tag i.image.url, class: "IMGIllust", width: "184", height: "184" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
                  <% end %>
                <% end %>
              </div>
              <div class="Illust_index">
                <%= link_to illust_path(i), style: "color: white;", data: {"turbolinks" => false} do %>
                  <%= i.title %>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

</div>

app/views/users/show_follow.html.erb
<div  class="div_wrapper">
    <div id="CARD" class="card">
      <div style="font-size: 25px;" class="card-header">
        Follow
      </div>
      <ul class="list-group list-group-flush">
        <div class="users">
          <% @user.following.each do |user| %>
            <li id="liGroup" class="list-group-item">
              <div class="current_user">
              <%= link_to user_path(user), data: {"turbolinks" => false} do %>
                <% if user.avatar? %>  <!-- アップロード画像がある場合に実行する -->
                 <%= image_tag user.avatar.url, class: "rounded-circle", id: "useravatar" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
                <% end %>
                <%= user.username %> 
              <% end %>
                  <% if user.id == current_user.id %>
                    <%= link_to "プロフィールを編集", edit_user_path(user), class: "Edit_profile", data: {"turbolinks" => false} %>
                  <% end %>
                
              </div>
            </li>
          <% end %>
        </div>
      </ul>
    </div>
</div> 

app/views/users/show_follower.html.erb
<div  class="div_wrapper">
    <div id="CARD" class="card">
      <div style="font-size: 25px;" class="card-header">
        Followers
      </div>
      <ul class="list-group list-group-flush">
        <div class="users">
          <% @user.followers.each do |user| %>
            <li id="liGroup" class="list-group-item">
              <div class="current_user">
                <%= link_to user_path(user), data: {"turbolinks" => false} do %>
                  <% if user.avatar? %>  <!-- アップロード画像がある場合に実行する -->
                    <%= image_tag user.avatar.url, class: "rounded-circle", id: "useravatar" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
                  <% end %>
                  <%= user.username %> 
                <% end %>
                  <% if user.id == current_user.id %>
                    <%= link_to "プロフィールを編集", edit_user_path(user), class: "Edit_profile", data: {"turbolinks" => false} %>
                  <% end %>
                
              </div>
            </li>
          <% end %>
        </div>
      </ul>
    </div>
</div>